### PR TITLE
Add "You cannot escape" to suggestions

### PR DESCRIPTION
**Pull request by wilkgr76**
LOL worthy :wink:

### CODE REVIEW

**Comment by srifqi** [comment]
Finally, somebody submit crazy idea. :laughing:

Have you better name for that? Also, would you mind to also edit [parameter.lua](https://github.com/srifqi/superflat/blob/master/parameter.lua) and [README.txt](https://github.com/srifqi/superflat/blob/master/README.txt) to include this? Don't forget to squash. :wink:

**Comment by wilkgr76** [comment]
@srifqi I'll do that.

**Comment by wilkgr76** [comment]
@srifqi Done! :smile:

**Comment by srifqi** [comment]
Can you do a [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits)?

**Comment by wilkgr76** [comment]
@srifqi Uhhhhhh...I'll try

**Comment by srifqi** [comment]
You have a Git client, right? If not, you can download [Github for Desktop](https://desktop.github.com). Then, do clone for your fork about this repository. Run command line. Then enter:

```
git rebase HEAD~4 -i
```

Then do what [this section](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) told.

After done, do
```
git push -f
```

Simple, right?

**Comment by srifqi** [comment]
Never mind, GitHub already has that feature in web interface.

Thanks for contributing!

**Pull request merged**
